MachinaIO/diamond-io

.github/workflows/ci.yml
Cargo.toml
README.md
benches/decompose_benchmark.rs
justfile
src/bgg/circuit/mod.rs
src/bgg/circuit/utils.rs
src/bgg/encoding.rs
src/bgg/sampler.rs
src/io/eval.rs
src/io/mod.rs
src/io/obf.rs
src/io/utils.rs
src/poly/dcrt/element.rs
src/poly/dcrt/matrix.rs
src/poly/dcrt/params.rs
src/poly/dcrt/poly.rs
src/poly/dcrt/sampler/hash.rs
src/poly/dcrt/sampler/trapdoor.rs
src/poly/dcrt/sampler/uniform.rs
src/poly/matrix.rs
src/poly/mod.rs
src/poly/params.rs
src/poly/sampler.rs
src/utils.rs

Core idea: I have a `S` matrix of size 2x12, `other` matrix of size 3x3 and identity `I` matrix of size 4x4. Goal is to perform `S * (I ⊗ other)`.
Current implementation: First perform `partial = (I ⊗ other)` and then `out = S * partial`.
Optimized implementation: Directly compute `out = S1*other | S2*other | S3*other | S4*other` where each `Si` is the slice of `S` of size 2 x 3
Results:
Reduced peak memory consumption from 4.78 GB to 353 MB
Improved performance
Before
```
Time to obfuscate: 139.643509375s
Time for evaluation: 102.822680333s
Total time: 242.466189708s
```
After
```
Time to obfuscate: 105.465769375s
Time for evaluation: 86.621996s
Total time: 192.087765375s
```

Optimize tensor operation

---

Cargo.toml
src/io/eval.rs
src/io/mod.rs
src/io/obf.rs
src/io/utils.rs
src/poly/dcrt/matrix.rs
src/poly/matrix.rs
src/utils.rs

Core idea: I have a `S` matrix of size 2x12, `other` matrix of size 3x3 and identity `I` matrix of size 4x4. Goal is to perform `S * (I ⊗ other)`.
Current implementation: First perform `partial = (I ⊗ other)` and then `out = S * partial`.
Optimized implementation: Directly compute `out = S1*other | S2*other | S3*other | S4*other` where each `Si` is the slice of `S` of size 2 x 3
Results after running `/usr/bin/time -l cargo test test_io_just_mul_enc_and_bit --release  -- --nocapture`
Before
```
Peak memory consumptions 4801904640  bytes (4.47 GB)
Time to obfuscate: 132.466593875s
Time for evaluation: 129.248957959s
Total time: 261.715551834s
```
After
```
Peak memory consumptions 542539776  bytes (0.51 GB)
Time to obfuscate: 105.465769375s
Time for evaluation: 116.751426959s
Total time: …
```

feat: apply tensor optimization

---

.github/workflows/ci.yml
benches/dcrtmatrix.rs
justfile
rust-toolchain.toml
src/bgg/circuit/mod.rs
src/bgg/circuit/utils.rs
src/bgg/encoding.rs
src/bgg/public_key.rs
src/bgg/sampler.rs
src/io/eval.rs
src/io/mod.rs
src/io/obf.rs
src/io/utils.rs
src/poly/dcrt/sampler/hash.rs
src/poly/dcrt/sampler/trapdoor.rs

- most of `rust fmt` features are only allowed on nightly. 
- TIL: `OpenFHE` installation have 3 step 
1. `cmake ..` : this will create `/build` folder
2. `make`
3. `sudo make install` : this installs in `"/usr/local"` ( including `local` and `included`).
it's tricky to cache"/usr/local/"` all on action (too large post cache took like 5m) 
so tempt to cache up to 2) step and do 3) which that's the what majority of time consumed anyway& slower than start from 1)
so looked up if there's any example that cache `OpenFHE` C++ binary somehow but e.g `openfhe-rs` just rebuild everytime, which I concluded for now it's works in this way. 
- so instead of caching fhe, at least this pr cache rust artifacts
resolving #15

chore:  nightly, ci split, rust cache

---

Cargo.toml
src/poly/dcrt/sampler/hash.rs
src/utils.rs

optimize hash sampler `sample` step by using `bitvec` representation instead of naive `Vec<u8>` ( aproximate: 8x memory efficient)

Perf: `bitvec!` hash sample

---

Cargo.toml
src/bgg/sampler.rs
src/io/eval.rs
src/io/mod.rs
src/io/obf.rs
src/io/utils.rs
src/poly/dcrt/matrix.rs
src/poly/dcrt/sampler/hash.rs
src/poly/dcrt/sampler/trapdoor.rs
src/poly/matrix.rs
src/utils.rs

`mul_tensor_identity_decompose` method on `PolyMatrix` performs the operation `S * (identity ⊗ G^-1(other))`, where G^-1(other) is bit decomposition of other matrix.
We introducing this optimization as `(identity ⊗ G^-1(other))` takes up too much memory. Instead, we chunk into column matrix and streaming multiplication with bit decomposed column and identity so to reduce peak memory consumption

Optimization `mul_tensor_identity_decompose`

---

README.md
src/bgg/sampler.rs
src/io/eval.rs
src/io/obf.rs
src/io/utils.rs
src/poly/dcrt/matrix.rs
src/poly/matrix.rs
src/utils.rs

before `decompose().get_column(0)`, first parse column vector matrix to make target decompose matrix size smaller
```
/usr/bin/time -l cargo test --test test_io --no-default-features --features parallel
```
```
test result: ok. 1 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 98.85s
100.35 real       787.32 user       233.41 sys
333807616  maximum resident set size
0  average shared memory size
0  average unshared data size
0  average unshared stack size
82128  page reclaims
122  page faults
0  swaps
0  block input operations
0  block output operations
0  messages sent
0  messages received
3  signals received
91  voluntary context switches
21956714  involuntary context switches
855483433  instructions retired
280632294  cycles elapsed
33031360  peak memory footprint …
```

perf: `.get_column_matrix_decompose`

---

Cargo.toml
README.md
src/io/obf.rs
src/poly/dcrt/sampler/hash.rs
src/poly/dcrt/sampler/trapdoor.rs
tests/test_io_dummy_param.rs
tests/test_io_real_param.rs

- split dummy param and real param test for easy build for memory profile 
- hash sampler parallel on index 
real param runs on linux
```
running 1 test
2025-03-24T08:37:18.129083Z  INFO diamond_io::utils: Sampled public data || Current physical/virtural memory usage: 4660285440 | 8555380736
test test::test_io_just_mul_enc_and_bit_real_params has been running for over 60 seconds
2025-03-24T08:44:35.839893Z  INFO diamond_io::utils: Sampled pub key init || Current physical/virtural memory usage: 14326321152 | 18740527104
2025-03-24T08:44:35.992379Z  INFO diamond_io::utils: Sampled s_bars || Current physical/virtural memory usage: 14326452224 | 18740527104
2025-03-24T08:44:36.161305Z  INFO diamond_io::utils: Sampled t_bar_matrix || Current physical/virtural memory usage: 14326452224 | …
```

feat: hash sampler parallel +split test

---

src/io/eval.rs
src/poly/dcrt/poly.rs
src/poly/polynomial.rs

Supports encoding of a polynomial into bytes.
We first loop over the coefficients to determine the `max_byte_size` needed to represent any of the poly coefficients. In the second loop we store each coefficient using `max_byte_size`. We expect to save some space compared to the current approach of storing each coefficient in `log2q` bits.
As a side note, I compared this encoding method with the one performed by openfhe in cpp (as described [here](https://hackmd.io/@MachinaIO/ry_TxaC2kl)) and it is much more efficient in terms of byte size. This is the result related various polynomials sampled from various distribution using our default parameters. As you can see the nature of our encoding is more dynamic. 
```
poly from binary - rust serialization: 6
poly from binary - cpp serialization : …
```

Add compact byte encoding for polynomial

---

Cargo.toml
src/poly/dcrt/poly.rs

Support to the new method `GetCoefficientsBytes` added on `openfhe-rs` -> https://github.com/MachinaIO/openfhe-rs/pull/1 .
Results show neglible differences in runtime and memory consumption between main and `feat/coeffs`

Replace `GetCoefficients` with  `GetCoefficientsBytes`

---

justfile
src/poly/dcrt/sampler/trapdoor.rs
src/poly/sampler.rs
src/utils.rs

Don't duplicate public matrix generation per each loop of the preimage sample step.
It doesn't have a memory advantage, but it has slight time advantage + nonduplicating logic
But this advantage becomes huge, especially if we were to use mmap(because if then `SetElement` takes too long).
before
```
2025-03-27T03:24:57.179890Z  INFO test_io_dummy_param::test: Time to obfuscate: 77.02023275s
2025-03-27T03:25:25.357265Z  INFO test_io_dummy_param::test: [false, false, false, true]
2025-03-27T03:25:25.357277Z  INFO test_io_dummy_param::test: Time for evaluation: 28.177009917s
2025-03-27T03:25:25.357279Z  INFO test_io_dummy_param::test: Total time: 105.197242667s
```
after
```
2025-03-27T03:37:40.327227Z  INFO test_io_dummy_param::test: Time to obfuscate: 74.563497625s …
```

feat: reuse public matrix for preimage

---

Cargo.toml
justfile
src/bgg/circuit/mod.rs
src/bgg/circuit/utils.rs
src/bgg/encoding.rs
src/bgg/norm_simulator.rs
src/bgg/public_key.rs
src/bgg/sampler.rs
src/io/eval.rs
src/io/obf.rs
src/io/utils.rs
src/poly/sampler.rs

remove unnecessary clone, define logic scope strictly on obfuscation
after (trivaial with https://github.com/MachinaIO/diamond-io/pull/56#issuecomment-2757207516)
```
2025-03-27T08:52:39.319165Z  INFO test_io_dummy_param::test: Time to obfuscate: 79.830405417s
2025-03-27T08:53:06.390972Z  INFO test_io_dummy_param::test: [false, false, false, true]
2025-03-27T08:53:06.390982Z  INFO test_io_dummy_param::test: Time for evaluation: 27.071620333s
2025-03-27T08:53:06.390984Z  INFO test_io_dummy_param::test: Total time: 106.90202575s
test test::test_io_just_mul_enc_and_bit ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 106.90s
Raw logs saved to logs/test_logs_20250327_175114.txt
===== COMBINED MEMORY USAGE =====
Step Description …
```

chore: obf clean

---

.github/workflows/ci.yml
Cargo.toml
README.md
justfile
src/bgg/circuit/eval.rs
src/bgg/circuit/mod.rs
src/bgg/sampler.rs
src/poly/dcrt/matrix.rs
src/poly/dcrt/poly.rs
src/poly/dcrt/sampler/hash.rs
src/poly/dcrt/sampler/trapdoor.rs
src/poly/dcrt/sampler/uniform.rs
src/utils.rs

- Topologically Sort and Iterate: basically return dependency order that ensures for any gate, all its dependencies (input gates) are processed before the gate itself
- with given dependency order, we no need perform recursive evaluation for prior gate like this (https://github.com/MachinaIO/diamond-io/blob/main/src/bgg/circuit/mod.rs#L228-L234) , so to reduce non necessary function call
- also removed `paralllel` feature as we not needed 
before
```
Time to obfuscate: 297.504950042s
Time for evaluation: 402.378013875s
Total time: 699.882963917s
```
after
```
Time to obfuscate: 285.641014709s
Time for evaluation: 385.333062416s
Total time: 670.974077125s
```

perf: circuit evaluation with dfs + chore: rm paralllel feature

---

memory_profile.py
src/bgg/circuit/mod.rs
src/bgg/circuit/utils.rs
src/io/eval.rs
src/io/mod.rs
src/io/obf.rs
src/io/utils.rs
src/poly/enc.rs
src/utils.rs
tests/test_io_dummy_param.rs
tests/test_io_middle_param.rs
tests/test_io_real_param.rs

In order to decrypt a ciphertext defined as `a_bit_0, b_bit_0, a_bit_1, b_bit_1, ..., a_bit_logq-1, b_bit_logq-1` the current implementation executes a circuit that performs, for each pair `a_bit, b_bit` the following inner product operation:
`a_bit * t_bar + b_bit * -1` which, overall, accounts for `2*log_q` multiplication gates per ciphertext.
In this proposed PR, the logic has been modified to directly pass `-t_bar` as circuit input and perform the operation `a_bit * -t_bar + b_bit` resulting in `log_q` multiplication gates per ciphertext.
At the same time, we had to modify the sign in the `rlwe_encrypt` logic
from 
```
b = t * a + e - (m * scale)
```
to 
```
b = t * a + e + (m * scale)
```
Benchmarks calculated on `uv run memory_profile.py cargo test -r --test test_io_middle_param …

Feat: optimize ip circuit

---

README.md
src/bgg/circuit/utils.rs
src/io/eval.rs
src/io/obf.rs
src/io/params.rs
src/io/utils.rs
tests/test_bgg_pubkey.rs
tests/test_io_dummy_param.rs
tests/test_io_dummy_param_width.rs
tests/test_io_middle_param.rs
tests/test_io_real_param.rs

Obfuscation now supports `level_width` which indicates the number of bits to be inserted at each diamond level
Right now we only support 1 bit insertion per step
While this is the new scenario when setting `level_width = 2` 
The advantage is that the noise growth of the p vector after 1 diamond step is the same in the two scenarios. Note the number of preimages to be generated at each diamond step is equal to 2^level_width_exp, namely every possible bit combination that can be inserted
`input_size = 4`
`level_width = 1`
```
cargo test -r --test test_io_dummy_param --no-default-features -- --nocapture
```
```
Time to obfuscate: 19.711899334s
Time for evaluation: 713.147916ms
Total time: 20.42504725s
```
`input_size = 4`
`level_width = 2`
```
cargo test -r --test test_io_dummy_param_width …
```

feat: larger width

---

src/io/eval.rs

Performance measured on `cargo test -r --test test_io_middle_param --no-default-features -- --nocapture`. The difference might be due to the volatility of the experiments given that no changes were applied to the obfuscation function.
`main`
```
Time to obfuscate: 534.466297584s
Time for evaluation: 131.70463175s
Total time: 666.170929334s
```
`feat/eval_refactor`
```
Time to obfuscate: 541.644143834s
Time for evaluation: 133.78545675s
Total time: 675.429600584s
```

feat: sample pubkey per level in eval.rs

---

simulator/main.py

This PR fixes a bug in `compute_obf_size` which used `base` rather than `base_bits` to compute `log_base_q`, causing too small `m` and `m_b` values regardless of the change of `base_bits`.

Fix a bug in compute_obf_size

---

dio/src/main.rs
src/io/eval.rs
src/io/mod.rs
src/test_utils.rs

The obfuscation artifacts are no longer loaded all at once during evaluation phase but dynamically when needed. Furthermore, for the `m, n, k` preimages, we are only loading the one related to the `num` input chosen by the evaluator.

Feat: just in time artifacts loading during evaluation phase

---

.github/workflows/benchmark.yml

finalizing benchmark workflow until feature of combining custom runner.
this ci checks openfhe installation, if not install, 
install latest `dio` binary and run bench base on provided input on CI.
After it upload log and memory analyzed file to github

ci: benchmark workflow 

---

README.md
dio/src/config.rs
e2e/dio-config.dummy.toml
src/io/serde.rs

fix dio config as we no need encoding sigma
check with https://github.com/MachinaIO/diamond-io/actions/runs/14901775460 ci

fix: rm encoding sigma

---

.github/workflows/benchmark-self-hosted.yml

The default job execution time is 6 hours.
For self-hosted runners we can configure a higher timeout-minutes value.
The execution timeout threshold was set to 4days

fix: The job has exceeded the maximum execution time

---

src/poly/dcrt/sampler/hash.rs

For reference, `test_poly_hash_sampler_fin_ring_dist` reduced 0.80s -> 0.35s 
instead of `BitVec` for allocation operation per each bits, use byte_buffer to save same allocation space + better run time. It needed for #146 where requires sample `r_k_s`
update: we may or may not need hash sampler for `r_k_s`, but for now #146 marked thoese facts as todo. Could consider this PR is just about performance for `FinRing` distribution for hashsampler

perf: optimize hash samper

---

dio/src/main.rs
simulator/main.py
src/bgg/lut/public_lut.rs
src/bgg/norm_simulator.rs
src/test_utils.rs

due to `max_output_row` introduced in #146 , we need to backup `t_num` for simulate bench so to initiate deterministic public lookup table.

fix add `t_num`

---

dio/src/main.rs
src/bgg/circuit/mod.rs
src/bgg/digits_to_int.rs
src/bgg/encoding.rs
src/poly/dcrt/matrix/dcrt_poly.rs
src/poly/dcrt/poly.rs
src/poly/enc.rs
src/poly/polynomial.rs
src/test_utils.rs

This is a real fix for PLT where the assertion is not working
: the issue was on `from_usize_to_lsb` method was previously overflowed at u64, so in real parameter case as the polynomial demension is over 64 bit, this lsb bit representation had repeated instead on filling up in 0. This is different behavior on our plaintext polynomial which is fully constant polynomial(only first few bytes are filled rest is 0). 
Also added some refactorings on methods as it was unclear what format of polynomial it returns via method name.
fixed benchmark: https://github.com/MachinaIO/diamond-io/actions/runs/16595490483/job/46941038176

fix: overflow while conversion
